# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to deploy'
        required: true
        default: master
env:
  NAME_GLOBAL: 'test-global'
  GLOBAL_LIST: '[ "bloups", "test-w" ]'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      NAME: 'test'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
          echo ${{ env.NAME }}
          echo ${{ env.NAME_GLOBAL }}
          echo ${{ github.event.repository.name }}
      - name: test-condition
        #if: contains(env.LIST_GLOBAL, ${{ github.event.repository.name }} )
        if: contains(fromJson(env.GLOBAL_LIST), github.event.repository.name)
        run: echo 'OK its in the list'
